version: "3"

tasks:
  migrations:
    aliases:
      - migrate
    desc: "Applies migrations to the database"
    cmds:
      - goose -dir ./migrations postgres "postgresql://SkaDin:05111996@localhost:5432/postgres" up
  start_application:
    aliases:
      - start
    desc: "Start applications"
    cmds:
      - go run cmd/sso/main.go --config=./config/local.yml

  test_app:
    aliases:
      - tests
    desc: "create test data apps"
    cmds:
      - goose -dir ./tests/migrations postgres "postgresql://SkaDin:05111996@localhost:5432/postgres" up